controllers:
    resource: '../src/Controller/'
    type: attribute
    exclude: '../src/Controller/Admin/'
    
admin_controllers:
    resource: '../src/Controller/Admin/'
    type: attribute
    prefix: /admin
